### PR TITLE
Some small improvements

### PR DESCRIPTION
**Pull request by InFog**
Hello!

Here are some small improvements. I hope it helps somehow ;)

### CODE REVIEW

**Comment by InFog** [comment]
Hey :) Any news here?

**Comment by hugofcampos** [comment]
:+1:

**Comment by fdiasdev** [comment]
@InFog the project is not going ahead in last days, but I have plans to do something asap

**Comment by fdiasdev** [comment]
@InFog thank you for the improvaments ;)

**Comment by InFog** [comment]
:smile:

**Pull request merged**
